### ISSUE TITLE
Issue using `setupProject` to prepare for spades workshop

### ISSUE THREAD

**Issue by VLucet** [PredictiveEcology/SpaDES.project#60]
I ran the following code, as indicated:

```R
repos <- c("predictiveecology.r-universe.dev", getOption("repos"))
install.packages("SpaDES.project", repos = repos, dependencies = TRUE)

library(SpaDES.project)

out <- setupProject(
    packages = "PredictiveEcology/PredictiveEcology.org@training-book/training/R/pkgList.R",
    options = list(repos = repos),
    name = "Introduction",
    modules = "PredictiveEcology/Biomass_core@main"
)
```

I get the following output/error:

```
setting up options...
  done setting up options
setting up paths ...
There is already a setLibPaths in the .Rprofile, skipping
Setting:
  options(
    reproducible.cachePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/cache'
    spades.inputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/inputs'
    spades.outputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/outputs'
    spades.modulePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/modules'
    spades.scratchPath = '/tmp/RtmpZVXQSU/Introduction'
  )
  done setting up paths
setting up modules...
                        moduleFullName        status
                                <char>        <char>
1: PredictiveEcology/Biomass_core@main already local
                                                    modulePath
                                                        <char>
1: /home/vlucet/Documents/WILDLab/spades/Introduction/modules/
  done setting up modules
setting up packages...
Installing any missing reqdPkgs
/home/vlucet/Documents/WILDLab/spades/Introduction/training/R/pkgList.R already exists; not downloading
                                                                          url     is             localFile
                                                                       <char> <char>                <char>
1: PredictiveEcology/PredictiveEcology.org@training-book/training/R/pkgList.R   ---> /training/R/pkgList.R
Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
  1 packages on GitHub
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In file(con, "r") :
  cannot open file '/home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION': No such file or directory
2: In FUN(X[[i]], ...) :
  Error in file(con, "r") : cannot open the connection

3: In file(con, "r") :
  cannot open file '/home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION': No such file or directory
4: In FUN(X[[i]], ...) :
  Error in file(con, "r") : cannot open the connection

5: In file(con, "r") :
  cannot open file '/home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION': No such file or directory
6: In FUN(X[[i]], ...) :
  Error in file(con, "r") : cannot open the connection

7: In file(con, "r") :
  cannot open file '/home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION': No such file or directory
Error in DESCRIPTIONFileDeps(DESCFile, which = c("Depends", "Imports",  : 
  Cannot read the file: /home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION
Error in grep(value = TRUE, pattern = deets, mp) : 
  invalid regular expression 'Error in DESCRIPTIONFileDeps(DESCFile, which = c("Depends", "Imports",  : 
  Cannot read the file: /home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION
', reason 'Missing ')''
In addition: Warning message:
In grep(value = TRUE, pattern = deets, mp) :
  TRE pattern compilation error 'Missing ')''
```

**Comment by CeresBarros** [comment]
Thank you for reporting this issue. We are diagnosing it

**Comment by eliotmcintire** [comment]
Diagnosed. Identifying a fix...

**Comment by eliotmcintire** [comment]
Fixed. Testing.

**Comment by eliotmcintire** [comment]
Fix pushed. It should be available within 1 hour

**Comment by eliotmcintire** [comment]
This is now fixed and in pushed to the `Require` package (this was a problem with a dependency, `Require`, not `SpaDES.project`)

**Comment by VLucet** [comment]
After updating to Require to `0.3.1.9089` , I am still unable to run the code
```
setting up options...
  done setting up options
setting up paths ...
There is already a setLibPaths in the .Rprofile, skipping
Setting:
  options(
    reproducible.cachePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/cache'
    spades.inputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/inputs'
    spades.outputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/outputs'
    spades.modulePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/modules'
    spades.scratchPath = '/tmp/RtmpDyFdLM/Introduction'
  )
  done setting up paths
setting up modules...
                        moduleFullName        status                                                  modulePath
                                <char>        <char>                                                      <char>
1: PredictiveEcology/Biomass_core@main already local /home/vlucet/Documents/WILDLab/spades/Introduction/modules/
  done setting up modules
setting up packages...
Installing any missing reqdPkgs
/home/vlucet/Documents/WILDLab/spades/Introduction/training/R/pkgList.R already exists; not downloading
                                                                          url     is             localFile
                                                                       <char> <char>                <char>
1: PredictiveEcology/PredictiveEcology.org@training-book/training/R/pkgList.R   ---> /training/R/pkgList.R
Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
  3 packages on GitHub
Error in file(con, "r") : cannot open the connection
In addition: There were 17 warnings (use warnings() to see them)
Error in DESCRIPTIONFileDeps(DESCFile, which = c("Depends", "Imports",  : 
  Cannot read the file: /home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION
Error in grep(value = TRUE, pattern = deets, mp) : 
  invalid regular expression 'Error in DESCRIPTIONFileDeps(DESCFile, which = c("Depends", "Imports",  : 
  Cannot read the file: /home/vlucet/.cache/R/Require/GitHub/ianmseddy_LandR.CS_Error in getSHAfromGitHub(...) : 
  Did you spell the GitHub.com repository, package and or branch/sha correctly?
_DESCRIPTION
', reason 'Missing ')''
In addition: Warning message:
In grep(value = TRUE, pattern = deets, mp) :
  TRE pattern compilation error 'Missing ')''
```

**Comment by VLucet** [comment]
This is fixed for me indeed - sorry please ignore the comment you might have seen, I deleted it.

**Comment by eliotmcintire** [comment]
NOte that the code has changed slightly for a better experience:
```
repos <- c("predictiveecology.r-universe.dev", getOption("repos"))
install.packages(c("Require", "SpaDES.project"), repos = repos)

library(SpaDES.project)

out <- setupProject(
  packages = "PredictiveEcology/PredictiveEcology.org@training-book/training/R/pkgList.R",
  options = list(repos = repos),
  name = "Introduction",
  modules = "PredictiveEcology/Biomass_core@main"
)
```

**Comment by VLucet** [comment]
Thanks for your patience, and apologies for the back and forth. I had missed that the code had changed slightly. I was able to run it successfully after:

1. Installing the system dependency `libarchive-dev` which I was missing and was requirde for the `archive` package.
2. Running `install.packages("lwgeom")` manually, as the installer seemed to fail to install `lwgeom`

The final, error free output after doing those 2 things was: 

```
setting up options...
  done setting up options
setting up paths ...
There is already a setLibPaths in the .Rprofile, skipping
Setting:
  options(
    reproducible.cachePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/cache'
    spades.inputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/inputs'
    spades.outputPath = '/home/vlucet/Documents/WILDLab/spades/Introduction/outputs'
    spades.modulePath = '/home/vlucet/Documents/WILDLab/spades/Introduction/modules'
    spades.scratchPath = '/tmp/RtmprpgDbE/Introduction'
  )
  done setting up paths
setting up modules...
                        moduleFullName        status                                                  modulePath
                                <char>        <char>                                                      <char>
1: PredictiveEcology/Biomass_core@main already local /home/vlucet/Documents/WILDLab/spades/Introduction/modules/
  done setting up modules
setting up packages...
Installing any missing reqdPkgs
/home/vlucet/Documents/WILDLab/spades/Introduction/training/R/pkgList.R already exists; not downloading
                                                                          url     is             localFile
                                                                       <char> <char>                <char>
1: PredictiveEcology/PredictiveEcology.org@training-book/training/R/pkgList.R   ---> /training/R/pkgList.R
No packages to install/update
  done setting up packages
.libPaths() are: /home/vlucet/.local/share/R/Introduction/packages/x86_64-pc-linux-gnu/4.4, /home/vlucet/.cache/R/renv/sandbox/R-4.4/x86_64-pc-linux-gnu/9a444a72
setting up options...
  done setting up options
  options changed:
   optionName
       <char>
1:      repos
                                                                                                        newValue
                                                                                                          <list>
1: predictiveecology.r-universe.dev,predictiveecology.r-universe.dev,https://packagemanager.posit.co/cran/latest
                                                                       oldValue
                                                                         <list>
1: predictiveecology.r-universe.dev,https://packagemanager.posit.co/cran/latest
```

**Comment by eliotmcintire** [comment]
You are on Linux, I presume

**Comment by CeresBarros** [comment]
@eliotmcintire  can we close?
